# Generated by Django 5.0.6 on 2024-06-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('encrypted_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
